### ISSUE TITLE
Error message on running ./runSModelS.py

### ISSUE THREAD

**Issue by juhidutta** [SModelS/smodels#34]
Dear experts,

I am currently using SModelS Release v2.3.2 (the zip version from github). While I have successfully installed it on centos7 system, I encounter the following error on running ./runSModelS.py -h:
 
Traceback (most recent call last):
  File "./runSModelS.py", line 3, in <module>
    from smodels.tools.runSModelS import main
  File "/raid05/users/jdutta/smodels-main/smodels/tools/runSModelS.py", line 12, in <module>
    from smodels.tools import modelTester
  File "/raid05/users/jdutta/smodels-main/smodels/tools/modelTester.py", line 16, in <module>
    from smodels.theory import theoryPrediction
  File "/raid05/users/jdutta/smodels-main/smodels/theory/theoryPrediction.py", line 16, in <module>
    from smodels.tools.statsTools import StatsComputer
  File "/raid05/users/jdutta/smodels-main/smodels/tools/statsTools.py", line 20, in <module>
    from smodels.tools.pyhfInterface import PyhfData, PyhfUpperLimitComputer
  File "/raid05/users/jdutta/smodels-main/smodels/tools/pyhfInterface.py", line 41, in <module>
    import pyhf
  File "/home/jdutta/.local/lib/python3.7/site-packages/pyhf/__init__.py", line 7, in <module>
    from pyhf.pdf import Model
  File "/home/jdutta/.local/lib/python3.7/site-packages/pyhf/pdf.py", line 11, in <module>
    from pyhf import schema
  File "/home/jdutta/.local/lib/python3.7/site-packages/pyhf/schema/__init__.py", line 6, in <module>
    from pyhf.schema.loader import load_schema
  File "/home/jdutta/.local/lib/python3.7/site-packages/pyhf/schema/loader.py", line 5, in <module>
    from pyhf.schema import variables
  File "/home/jdutta/.local/lib/python3.7/site-packages/pyhf/schema/variables.py", line 9, in <module>
    schemas = resources.files('pyhf') / "schemas"
AttributeError: module 'importlib_resources' has no attribute 'files'

Could you please kindly advise how I may resolve this error? 

Best regards,
Juhi

**Comment by WolfgangWaltenberger** [comment]
Hey Juhi,

long time no see! The error is an issue with pyhf, the code reads

if sys.version_info >= (3, 9):
    from importlib import resources
else:
    import importlib_resources as resources

Is there any way you can just use a python version >= 3.9?
If you really need python 3.7 and pyhf and you have the latest
importlib_resources module,
then I suggest contacting the pyhf team about this.

Cheers

Wolfgang

**Comment by juhidutta** [comment]
Hi Wolfgang,

Thank you for your response.

I will upgrade importlib_resources and retry again on the cluster.
Meanwhile, it runs successfully on a Ubuntu system.

With best regards,
Juhi
